@echo off
REM ===================================================================
REM  build_mecab_win.bat -- Build MeCab from source and install to prefix
REM  Run from a VS x64 Native Tools Command Prompt (or any shell after
REM  vcvarsall.bat x64).  Similar to the CTranslate2 build workflow.
REM
REM  Prerequisites: the MeCab source at C:\mecab must already have the
REM  three MSVC compatibility patches applied (common.h WPATH_FORCE,
REM  dictionary.cpp binary_function, writer.cpp size_t cast).
REM  See yip_os/docs/BUILD_MECAB_WIN.md for details.
REM ===================================================================

setlocal enabledelayedexpansion

REM --- VS environment ---
if defined VSCMD_VER goto :skip_vcvars
call "C:\Program Files (x86)\Microsoft Visual Studio\18\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" x64
:skip_vcvars

REM --- Configuration ---
set "MECAB_SRC=C:\mecab"
set "MECAB_PREFIX=C:\mecab_install"

echo.
echo ============================================================
echo  MeCab Windows x64 build script
echo  Source:  %MECAB_SRC%
echo  Install: %MECAB_PREFIX%
echo ============================================================
echo.

REM --- Step 1: Clone MeCab if not present ---
if exist "%MECAB_SRC%\mecab\src\libmecab.cpp" (
    echo MeCab source already exists at %MECAB_SRC%, skipping clone.
) else (
    echo Cloning MeCab...
    git clone https://github.com/taku910/mecab.git "%MECAB_SRC%"
    if errorlevel 1 (
        echo ERROR: git clone failed.
        exit /b 1
    )
)

pushd "%MECAB_SRC%\mecab\src"

REM --- Step 2: Generate config.h for MSVC ---
REM MeCab was designed for autotools.  The upstream source has no MSVC config.h,
REM so we generate one with the values from Makefile.msvc.in / configure.in.
echo --- Generating config.h for MSVC ---
(
echo /* config.h -- generated by build_mecab_win.bat for MSVC x64 */
echo #ifndef MECAB_CONFIG_H_
echo #define MECAB_CONFIG_H_
echo.
echo #define HAVE_WINDOWS_H 1
echo #define HAVE_GETENV 1
echo #define HAVE_STRING_H 1
echo #define HAVE_STDLIB_H 1
echo #define HAVE_STDINT_H 1
echo #define HAVE_IO_H 1
echo.
echo #define DIC_VERSION 102
echo #define VERSION "0.996"
echo #define PACKAGE "mecab"
echo #define MECAB_DEFAULT_RC "mecabrc"
echo.
echo #define SIZEOF_CHAR 1
echo #define SIZEOF_SHORT 2
echo #define SIZEOF_INT 4
echo #define SIZEOF_LONG 4
echo #define SIZEOF_LONG_LONG 8
echo #define SIZEOF_SIZE_T 8
echo.
echo #define HAVE_UNSIGNED_LONG_LONG_INT 1
echo.
echo #endif
) > config.h
echo config.h generated.

REM --- Step 3: Clean previous build artifacts ---
del /Q *.obj *.dll *.lib *.exp 2>nul

REM --- Step 4: Build libmecab.dll ---
echo.
echo --- Building libmecab.dll (x64) ---
cl /EHsc /O2 /MD /DDLL_EXPORT /DMECAB_USE_UTF8_ONLY /DHAVE_CONFIG_H ^
   /DUNICODE /D_UNICODE /D_CRT_SECURE_NO_DEPRECATE ^
   /I. /LD /Fe:libmecab.dll ^
   char_property.cpp connector.cpp context_id.cpp dictionary.cpp ^
   dictionary_compiler.cpp dictionary_generator.cpp dictionary_rewriter.cpp ^
   eval.cpp feature_index.cpp iconv_utils.cpp lbfgs.cpp learner.cpp ^
   learner_tagger.cpp libmecab.cpp nbest_generator.cpp param.cpp ^
   string_buffer.cpp tagger.cpp tokenizer.cpp utils.cpp viterbi.cpp ^
   writer.cpp ^
   /link advapi32.lib
if errorlevel 1 (
    echo ERROR: libmecab.dll build failed.
    popd
    exit /b 1
)
echo libmecab.dll built OK.

REM --- Step 5: Build mecab-dict-index.exe ---
echo.
echo --- Building mecab-dict-index.exe ---
del /Q *.obj 2>nul
cl /EHsc /O2 /MD /DMECAB_USE_UTF8_ONLY /DHAVE_CONFIG_H ^
   /DUNICODE /D_UNICODE /D_CRT_SECURE_NO_DEPRECATE ^
   /I. /Fe:mecab-dict-index.exe ^
   dictionary_compiler.cpp dictionary_generator.cpp dictionary_rewriter.cpp ^
   char_property.cpp connector.cpp context_id.cpp eval.cpp ^
   feature_index.cpp iconv_utils.cpp lbfgs.cpp param.cpp ^
   string_buffer.cpp tagger.cpp tokenizer.cpp utils.cpp viterbi.cpp ^
   writer.cpp nbest_generator.cpp learner.cpp learner_tagger.cpp ^
   dictionary.cpp libmecab.cpp mecab-dict-index.cpp ^
   /link advapi32.lib
if errorlevel 1 (
    echo ERROR: mecab-dict-index.exe build failed.
    popd
    exit /b 1
)
echo mecab-dict-index.exe built OK.
popd

REM --- Step 6: Compile ipadic dictionary (EUC-JP -> UTF-8) ---
echo.
echo --- Compiling ipadic dictionary (EUC-JP to UTF-8) ---
pushd "%MECAB_SRC%\mecab-ipadic"
if not exist compiled mkdir compiled
"%MECAB_SRC%\mecab\src\mecab-dict-index.exe" -d . -o compiled -f euc-jp -t utf-8
if errorlevel 1 (
    echo ERROR: Dictionary compilation failed.
    popd
    exit /b 1
)
REM dicrc is NOT generated by mecab-dict-index — copy it from source
copy /Y dicrc compiled\
echo ipadic dictionary compiled OK.
popd

REM --- Step 7: Install to prefix ---
echo.
echo --- Installing to %MECAB_PREFIX% ---
if not exist "%MECAB_PREFIX%\bin"        mkdir "%MECAB_PREFIX%\bin"
if not exist "%MECAB_PREFIX%\lib"        mkdir "%MECAB_PREFIX%\lib"
if not exist "%MECAB_PREFIX%\include"    mkdir "%MECAB_PREFIX%\include"
if not exist "%MECAB_PREFIX%\dic\ipadic" mkdir "%MECAB_PREFIX%\dic\ipadic"

copy /Y "%MECAB_SRC%\mecab\src\libmecab.dll" "%MECAB_PREFIX%\bin\"
copy /Y "%MECAB_SRC%\mecab\src\libmecab.lib" "%MECAB_PREFIX%\lib\"
copy /Y "%MECAB_SRC%\mecab\src\mecab.h"      "%MECAB_PREFIX%\include\"
xcopy /Y /Q "%MECAB_SRC%\mecab-ipadic\compiled\*.*" "%MECAB_PREFIX%\dic\ipadic\"

REM --- Verify ---
echo.
echo ============================================================
if exist "%MECAB_PREFIX%\lib\libmecab.lib" (
    if exist "%MECAB_PREFIX%\bin\libmecab.dll" (
        if exist "%MECAB_PREFIX%\dic\ipadic\sys.dic" (
            echo  SUCCESS: MeCab installed to %MECAB_PREFIX%
            echo.
            echo  lib:     %MECAB_PREFIX%\lib\libmecab.lib
            echo  dll:     %MECAB_PREFIX%\bin\libmecab.dll
            echo  header:  %MECAB_PREFIX%\include\mecab.h
            echo  dict:    %MECAB_PREFIX%\dic\ipadic\
            echo.
            echo  Run build_win.bat -- you should see:
            echo    MeCab found at %MECAB_PREFIX%
        ) else (
            echo  WARNING: Dictionary not found -- sys.dic missing from dic\ipadic
        )
    ) else (
        echo  WARNING: libmecab.dll not found in bin\
    )
) else (
    echo  WARNING: libmecab.lib not found in lib\
)
echo ============================================================

endlocal
